# Welcome to Jekyll Paper for Github
#
# This is the configuration file for your blog, please change these items after forked.

title: wqt
email: 
name: 
description: >- # this means to ignore newlines until "baseurl:"
  Welder Qualification Test.
keywords: []
baseurl: '/wqt' # the subpath of your site, e.g. /`blog
url: 'https://yakimk.github.io/wqt/' # the base hostname & protocol for your site, e.g. http://example.com
domain: 'yakimk.github.io/wqt/' # the domain name for your site, e.g. example.com
language: en
# Supported languages list:
# en: English
# de: Deutsche (German)
# es: Español (Spanish)
# fr: Français (French)
# ja: 日本語 (Japanese)
# pt: Português (Portuguese)
# zh-cn: 简体中文 (Simplified Chinese)
# zh-tw: 繁體中文 (Traditional Chinese)
# ko : 한국어 (Korean)

analytics: # the Google Analytics property ID, e.g. UA-XXXXX-Y

comments: true # enable comments
disqus: # disqus account

mathjax: false # Math support
diagram: true # Diagrams support

paginate: 25
paginate_path: '/page:num/'

permalink: /:year/:month/:day/:title

sass:
  sass_dir: _sass
  style: expanded # compressed, compact, expanded or compressed

# Build settings
markdown: kramdown
kramdown:
    auto_ids: true

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-katex
  - jekyll-toc

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

defaults:
  - scope:
      path: "courses"
      type: "pages"
    values:
      permalink: /:path/:basename

toc:
  enabled: true
  min_heading_level: 2    # Minimum heading level to include in the TOC (default is h2)
  max_heading_level: 3    # Maximum heading level (default is h3)
  ordered: true